server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carzone?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    # Druid datasource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # ?????
      initial-size: 5
      # ?????
      min-idle: 10
      # ?????
      max-active: 20
      # ????????????
      max-wait: 60000
      # ????????????????????
      min-evictable-idle-time-millis: 300000
      # ????????????????????????
      time-between-eviction-runs-millis: 60000
      # ???????stat-?????log4j-???wall-??????SQL?????????????sql????
      filters: stat,wall
      # ????????? SQL???????????????
      validation-query: SELECT 1
      # ???????validationQuery???????????true?????????
      test-on-borrow: true
      # ???????validationQuery???????????false?????????
      test-on-return: true
      # ?????????????timeBetweenEvictionRunsMillis???validationQuery???????????false???????????
      test-while-idle: true
      # ???? StatViewServlet
      stat-view-servlet:
        enabled: true
        # ?????? ??????127.0.0.1
        allow: 127.0.0.1
        login-username: root
        login-password: 123456
      # FilterStat
      filter:
        stat:
          # ???? FilterStat???true
          enabled: true
          # ???? ?SQL ?????false
          log-slow-sql: true
          # ? SQL ?????? 3000??????
          slow-sql-millis: 5000
          # ???????????????false
          merge-sql: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
